### ISSUE TITLE
Vignette Build Failed, preventing install

### ISSUE THREAD

**Issue by warnost** [josephsdavid/tswgewrapped#30]
I ran the command devtools::install_github("josephsdavid/tswgewrapped", build_vignettes = TRUE) and got this error:

Error: Failed to install 'tswgewrapped' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Quitting from lines 69-70 (ModelCompareUnivariate.Rmd) 
E> Error: processing vignette 'ModelCompareUnivariate.Rmd' failed with diagnostics:
E> Can't combine `..1$Realization` <character> and `..2$Realization` <integer>.
E> --- failed re-building 'ModelCompareUnivariate.Rmd'
E> 
E> SUMMARY: processing the following files failed:
E>   'ModelBuildMultivariateVAR.Rmd' 'ModelCompareUnivariate.Rmd'
E> 
E> Error: Vignette re-building failed.
E> Execution halted

I ran the command devtools::install_github("josephsdavid/tswgewrapped", build_vignettes = FALSE)  and the install worked. Just wanted to make you guys aware. Thanks!

**Comment by ngupta23** [comment]
Hi @warnost , please try installing without the vignettes. I updated the [Readme](https://github.com/josephsdavid/tswgewrapped/blob/master/Readme.md) to indicate the same.

```
NOTE: If you face issues with vignettes during installation, try with build_vignettes = FALSE
```

**Comment by ngupta23** [comment]
Hi @warnost  Did this resolve your issue?

**Comment by warnost** [comment]
Hi @ngupta23 Yes, setting build_vignettes = FALSE worked for me. Thank you!
